spring:
  datasource:
    url: jdbc:mysql://${MYSQL_DB_HOST:localhost}:3306/consumer?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    tomcat:
      test-while-idle: true
      validation-query: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect